# Generated by Django 4.2 on 2023-04-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem', models.CharField(max_length=50, verbose_name='Драгоценный камень')),
                ('total', models.PositiveIntegerField(verbose_name='Сумма')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество (шт)')),
                ('date', models.DateTimeField(verbose_name='Время совершения сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
